/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package concatwfm;

import Classes.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luciano.benfica
 */
public class JFAtualizaBD extends javax.swing.JFrame {

    /**
     * Creates new form JFAtualizaBD
     */
    public JFAtualizaBD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        atualizaBancojButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        arqNaRedejLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeArqRedejLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gradepathjTable = new javax.swing.JTable();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        caminhoNaRedejTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tabuladorjTextField = new javax.swing.JTextField();
        nomeBasejTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        buscarjButton = new javax.swing.JButton();
        novojButton = new javax.swing.JButton();
        editarjButton = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        salvarjButton = new javax.swing.JButton();
        alterarjButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        excluirjButton = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        cancelarjButton = new javax.swing.JButton();
        limparjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        atualizaBancojButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/banco_dados2_16.png"))); // NOI18N
        atualizaBancojButton.setText("Atualiza banco");
        atualizaBancojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizaBancojButtonActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel1.setText("Qtd de arquivos na rede:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nome do arquivo:");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(atualizaBancojButton)
                    .addComponent(jButton1))
                .addGap(38, 38, 38)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(arqNaRedejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nomeArqRedejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
                .addContainerGap(276, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(arqNaRedejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(nomeArqRedejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(atualizaBancojButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Controle de atualizações", jPanel3);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        gradepathjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id#", "Caminho da rede", "Tabulador", "Nome da base"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gradepathjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gradepathjTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(gradepathjTable);
        gradepathjTable.getColumnModel().getColumn(0).setResizable(false);
        gradepathjTable.getColumnModel().getColumn(0).setPreferredWidth(10);
        gradepathjTable.getColumnModel().getColumn(1).setResizable(false);
        gradepathjTable.getColumnModel().getColumn(1).setPreferredWidth(400);
        gradepathjTable.getColumnModel().getColumn(2).setResizable(false);
        gradepathjTable.getColumnModel().getColumn(2).setPreferredWidth(10);
        gradepathjTable.getColumnModel().getColumn(3).setResizable(false);
        gradepathjTable.getColumnModel().getColumn(3).setPreferredWidth(10);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Caminho na rede");

        jLabel4.setText("Tabulador");

        jLabel5.setText("Nome da base");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Legenda tabulador / usar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 204)));

        jLabel6.setText("Comma/vírgula");

        jLabel7.setText("Ponto e vírgula");

        jLabel8.setText("Pipe");

        jLabel9.setText("Tabulação");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel10.setText(",");

        jLabel11.setText(";");

        jLabel12.setText("|");

        jLabel13.setText("\\t");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel9))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToolBar1.setBackground(new java.awt.Color(155, 155, 155));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        buscarjButton.setBackground(new java.awt.Color(155, 155, 155));
        buscarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/buscar.png"))); // NOI18N
        buscarjButton.setText("Buscar");
        buscarjButton.setToolTipText("Consultar");
        buscarjButton.setFocusable(false);
        buscarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buscarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buscarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(buscarjButton);

        novojButton.setBackground(new java.awt.Color(155, 155, 155));
        novojButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/new2.png"))); // NOI18N
        novojButton.setText("Novo");
        novojButton.setToolTipText("Novo cadastro");
        novojButton.setFocusable(false);
        novojButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        novojButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        novojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novojButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(novojButton);

        editarjButton.setBackground(new java.awt.Color(155, 155, 155));
        editarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/edit.png"))); // NOI18N
        editarjButton.setText("Editar");
        editarjButton.setFocusable(false);
        editarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(editarjButton);
        jToolBar1.add(jSeparator4);

        salvarjButton.setBackground(new java.awt.Color(155, 155, 155));
        salvarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/save.png"))); // NOI18N
        salvarjButton.setText("Salvar");
        salvarjButton.setToolTipText("Salvar");
        salvarjButton.setFocusable(false);
        salvarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salvarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        salvarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(salvarjButton);

        alterarjButton.setBackground(new java.awt.Color(155, 155, 155));
        alterarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/save2.png"))); // NOI18N
        alterarjButton.setText("Alterar");
        alterarjButton.setToolTipText("Alterar cadastro");
        alterarjButton.setFocusable(false);
        alterarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        alterarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        alterarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(alterarjButton);
        jToolBar1.add(jSeparator3);

        excluirjButton.setBackground(new java.awt.Color(155, 155, 155));
        excluirjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/delete.png"))); // NOI18N
        excluirjButton.setText("Excluir");
        excluirjButton.setFocusable(false);
        excluirjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        excluirjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(excluirjButton);
        jToolBar1.add(jSeparator5);

        cancelarjButton.setBackground(new java.awt.Color(155, 155, 155));
        cancelarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Cancel.png"))); // NOI18N
        cancelarjButton.setText("Cancelar");
        cancelarjButton.setFocusable(false);
        cancelarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancelarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(cancelarjButton);

        limparjButton.setBackground(new java.awt.Color(155, 155, 155));
        limparjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/clear.png"))); // NOI18N
        limparjButton.setText("Limpar");
        limparjButton.setFocusable(false);
        limparjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        limparjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        limparjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(limparjButton);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(caminhoNaRedejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tabuladorjTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeBasejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel3)
                        .addGap(5, 5, 5)
                        .addComponent(caminhoNaRedejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tabuladorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeBasejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Configurar caminho das bases", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private int count = 0;
    private File file;
    private String nome_do_arquivo;
    private int numero_linha = 0;
    private String caminho_do_arquivo;
    private int click_path;
    ClassConecta conecta = new ClassConecta();

    private void contaArquivosNaRede() {
        caminho_do_arquivo = "C:\\teste\\BASES_TESTE\\";
        file = new File(caminho_do_arquivo);
        count = file.listFiles().length;

        arqNaRedejLabel.setText(String.valueOf(count));

    }

    private void atualizaBaseSS() {

        List<String> linhas_lista = new ArrayList<>();


        File[] arquivos = file.listFiles();

        for (File arquivo : arquivos) {

            nome_do_arquivo = arquivo.getName();
            nomeArqRedejLabel.setText(nome_do_arquivo);


            File path = new File(caminho_do_arquivo + nome_do_arquivo);

            try {

                FileReader reader = new FileReader(path);
                try (BufferedReader input = new BufferedReader(reader)) {
                    String linha;


                    while ((linha = input.readLine()) != null) {
//                        System.out.println(linha);
//                            linhas_lista.add(linha);
                        String[] colunas = linha.split("\t");

//                        
                        if (linha == null) {
                            break;
                        }

                        System.out.println(colunas[0] + " - "
                                + colunas[2] + " - "
                                + colunas[3] + " - "
                                + colunas[4] + " - "
                                + colunas[5] + " - "
                                + colunas[6] + " - "
                                + colunas[7] + " - "
                                + colunas[8] + " - "
                                + colunas[9] + " - "
                                + colunas[10] + " - "
                                + colunas[11] + " - "
                                + colunas[12] + " - "
                                + colunas[13] + " - "
                                + colunas[14] + " - "
                                + colunas[15] + " - "
                                + colunas[16] + " - "
                                + colunas[17] + " - "
                                + colunas[18] + " - "
                                + colunas[19] + " - "
                                + colunas[20] + " - "
                                + colunas[21] + " - "
                                + colunas[22] + " - "
                                + colunas[23] + " - "
                                + colunas[24] + " - "
                                + colunas[25] + " - "
                                + colunas[26] + " - "
                                + colunas[27] + " - "
                                + colunas[28] + " - "
                                + colunas[29] + " - "
                                + colunas[30] + " - "
                                + colunas[31] + " - "
                                + colunas[32] + " - "
                                + colunas[33] + " - "
                                + colunas[34] + " - "
                                + colunas[35] + " - "
                                + colunas[36] + " - "
                                + colunas[37] + " - "
                                + colunas[38] + " - "
                                + colunas[39] + " - "
                                + colunas[40] + " - "
                                + colunas[41] + " - "
                                + colunas[42] + " - "
                                + colunas[43] + " - "
                                + colunas[44] + " - "
                                + colunas[45] + " - "
                                + colunas[46] + " - "
                                + colunas[47] + " - "
                                + colunas[48] + " - "
                                + colunas[49] + " - "
                                + colunas[50] + " - "
                                + colunas[51] + " - "
                                + colunas[52] + " - "
                                + colunas[53] + " - "
                                + colunas[54] + " - "
                                + colunas[55] + " - "
                                + colunas[56] + " - "
                                + colunas[57] + " - "
                                + colunas[58] + " - "
                                + colunas[59] + " - "
                                + colunas[60] + " - "
                                + colunas[61] + " - "
                                + colunas[62] + " - "
                                + colunas[63] + " - "
                                + colunas[64] + " - "
                                + colunas[65] + " - "
                                + colunas[66] + " - "
                                + colunas[67] + " - "
                                + colunas[68] + " - "
                                + colunas[69] + " - "
                                + colunas[70] + " - "
                                + colunas[71] + " - "
                                + colunas[72] + " - "
                                + colunas[73] + " - "
                                + colunas[74] + " - "
                                + colunas[75] + " - "
                                + colunas[76] + " - "
                                + colunas[77] + " - "
                                + colunas[78] + " - "
                                + colunas[79] + " - "
                                + colunas[80] + " - "
                                + colunas[81] + " - "
                                + colunas[82] + " - "
                                + colunas[83] + " - "
                                + colunas[84] + " - "
                                + colunas[85] + " - "
                                + colunas[86] + " - "
                                + colunas[87] + " - "
                                + colunas[88] + " - "
                                + colunas[89] + " - "
                                + colunas[90] + " - "
                                + colunas[91] + " - "
                                + colunas[92] + " - "
                                + colunas[93] + " - "
                                + colunas[94] + " - "
                                + colunas[95] + " - "
                                + colunas[96] + " - "
                                + colunas[97] + " - "
                                + colunas[98] + " - "
                                + colunas[99] + " - "
                                + colunas[100] + " - "
                                + colunas[101] + " - "
                                + colunas[102] + " - "
                                + colunas[103] + " - "
                                + colunas[104] + " - "
                                + colunas[105] + " - "
                                + colunas[106] + " - "
                                + colunas[107] + " - "
                                + colunas[108] + " - "
                                + colunas[109] + " - "
                                + colunas[110] + " - "
                                + colunas[111] + " - "
                                + colunas[112]
                                );

//                        System.out.println(colunas[0].replaceAll("\"", "") + " " + colunas[1].replaceAll("\"", "")
//                                + " " + colunas[2].replaceAll("\"", "") + " " + colunas[3].replaceAll("\"", ""));

                        numero_linha = numero_linha + 1;
//                        jLabel1.setText(String.valueOf(numero_linha));
                        arqNaRedejLabel.update(getGraphics());
                    }

                }



            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao importar\n" + e, "mensagem do sistema", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }

//            JOptionPane.showMessageDialog(null, nome_do_arquivo);
//            System.out.println(arquivo);
        }
    }

    public void getGrandePath() throws ParseException {
        //Consultar caminho da rede
        CaminhoRedeReport oPath = new CaminhoRedeReport();

        ResultSet resultSet = null;

        String[] colunasTabela = new String[]{"Id#", "caminho da rede", "Tabulador", "Nome da base"};
        DefaultTableModel modeloTabela = new DefaultTableModel(null, colunasTabela) {

            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        gradepathjTable.setModel(modeloTabela);
        gradepathjTable.getColumnModel().getColumn(0).setPreferredWidth(10);
        gradepathjTable.getColumnModel().getColumn(1).setPreferredWidth(500);
        gradepathjTable.getColumnModel().getColumn(2).setPreferredWidth(10);
        gradepathjTable.getColumnModel().getColumn(3).setPreferredWidth(10);

        try {

            resultSet = oPath.getConsultar();

            if (resultSet.getRow() == 1) {
                resultSet.first();
            }


        } catch (SQLException ex) {
            Logger.getLogger(Funcionarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {

            while (resultSet.next()) {

                modeloTabela.addRow(new String[]{
                            resultSet.getString("ID"),
                            resultSet.getString("CAMINHO"),
                            resultSet.getString("TABULADOR"),
                            resultSet.getString("PASTA"),});

            }

        } catch (SQLException ex) {
            Logger.getLogger(Funcionarios.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void getFieldPath(int click_path) throws ParseException {

        CaminhoRedeReport oPath = new CaminhoRedeReport();
        ResultSet rs;
        oPath.setId(click_path);

        try {
            rs = oPath.getConsultar();
            rs.next();

            //Pegar campos
            caminhoNaRedejTextField.setText(rs.getString("CAMINHO"));
            tabuladorjTextField.setText(rs.getString("TABULADOR"));
            nomeBasejTextField.setText(rs.getString("PASTA"));

        } catch (SQLException ex) {
            Logger.getLogger(Funcionarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        novojButton.setVisible(true);
        editarjButton.setVisible(false);
        salvarjButton.setVisible(false);
        alterarjButton.setVisible(false);
        excluirjButton.setVisible(false);
        try {
            ClassConecta.conecta();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao abrir conexão com o banco de dados\n" + e, "mensagem do sistema", JOptionPane.ERROR_MESSAGE);
        }
        buscarjButtonActionPerformed(null);
    }//GEN-LAST:event_formWindowOpened

    private void atualizaBancojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizaBancojButtonActionPerformed
        // TODO add your handling code here:
        AtualizaBaseSS oBaseSS = new AtualizaBaseSS();
        
        contaArquivosNaRede();
        
//        String extencao = nome_do_arquivo.substring(nome_do_arquivo.length()-4);
//        String data = extencao.substring(extencao.length()-10);
//        System.out.println("Data do arquivo" + data);
        
        

        oBaseSS.atualizaBaseSS(file, nome_do_arquivo, caminho_do_arquivo);


    }//GEN-LAST:event_atualizaBancojButtonActionPerformed

    private void novojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novojButtonActionPerformed
        // TODO add your handling code here:
        novojButton.setVisible(false);
        editarjButton.setVisible(false);
        buscarjButton.setVisible(true);
        salvarjButton.setVisible(true);
        alterarjButton.setVisible(true);
        caminhoNaRedejTextField.grabFocus();

        try {
            ClassConecta.con.setAutoCommit(false);
        } catch (Exception e) {
        }
        limparjButtonActionPerformed(evt);
    }//GEN-LAST:event_novojButtonActionPerformed

    private void limparjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparjButtonActionPerformed
        // TODO add your handling code here:
        caminhoNaRedejTextField.setText("");
        tabuladorjTextField.setText("");
        nomeBasejTextField.setText("");
    }//GEN-LAST:event_limparjButtonActionPerformed

    private void salvarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarjButtonActionPerformed
        // TODO add your handling code here:
        if (caminhoNaRedejTextField.getText().isEmpty()
                || tabuladorjTextField.getText().isEmpty()
                || nomeBasejTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Atenção!\nTodos os campos são obrigatórios.", "Mensagem do sistema", JOptionPane.WARNING_MESSAGE);
        } else {

            try {

                CaminhoRedeReport oPath = new CaminhoRedeReport();

                oPath.setCaminho_rede(caminhoNaRedejTextField.getText().trim().toLowerCase());
                oPath.setTabulador(tabuladorjTextField.getText().trim().toLowerCase());
                oPath.setNome_base(nomeBasejTextField.getText().trim().toUpperCase());
                oPath.setCadastrar();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar.\n" + e, "Mensagem do sistema", JOptionPane.ERROR_MESSAGE);
            }
            buscarjButtonActionPerformed(evt);
        }
    }//GEN-LAST:event_salvarjButtonActionPerformed

    private void buscarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarjButtonActionPerformed
        // TODO add your handling code here:
        try {
            getGrandePath();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar a grade.\n" + e, "Mensagem do sistema", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buscarjButtonActionPerformed

    private void editarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarjButtonActionPerformed
        // TODO add your handling code here:
        novojButton.setVisible(false);
        salvarjButton.setVisible(false);
        editarjButton.setVisible(false);
        alterarjButton.setVisible(true);
        excluirjButton.setVisible(true);
        try {
            ClassConecta.con.setAutoCommit(false);
        } catch (SQLException ex) {
            Logger.getLogger(Funcionarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editarjButtonActionPerformed

    private void alterarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarjButtonActionPerformed
        // TODO add your handling code here:
        if (caminhoNaRedejTextField.getText().isEmpty()
                || tabuladorjTextField.getText().isEmpty()
                || nomeBasejTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Atenção!\nTodos os campos são obrigatórios.", "Mensagem do sistema", JOptionPane.WARNING_MESSAGE);
        } else {

            try {

                CaminhoRedeReport oPath = new CaminhoRedeReport();
                
                oPath.setId(click_path);

                oPath.setCaminho_rede(caminhoNaRedejTextField.getText().trim().toLowerCase());
                oPath.setTabulador(tabuladorjTextField.getText().trim().toLowerCase());
                oPath.setNome_base(nomeBasejTextField.getText().trim().toUpperCase());
                oPath.setAlterar(conecta);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar.\n" + e, "Mensagem do sistema", JOptionPane.ERROR_MESSAGE);
            }
            buscarjButtonActionPerformed(evt);
        }
    }//GEN-LAST:event_alterarjButtonActionPerformed

    private void gradepathjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradepathjTableMouseClicked
        // TODO add your handling code here:
        editarjButton.setVisible(true);

        click_path = Integer.parseInt(gradepathjTable.getValueAt(gradepathjTable.getSelectedRow(), 0).toString());
        try {
            getFieldPath(click_path);
        } catch (ParseException ex) {
            Logger.getLogger(JFAtualizaBD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_gradepathjTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String digitos = "1234567890.txt";
        String ultimos = digitos.replace(".txt", "").substring(digitos.length()-8);
        System.out.println(ultimos);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFAtualizaBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFAtualizaBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFAtualizaBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFAtualizaBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new JFAtualizaBD().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarjButton;
    private javax.swing.JLabel arqNaRedejLabel;
    private javax.swing.JButton atualizaBancojButton;
    private javax.swing.JButton buscarjButton;
    private javax.swing.JTextField caminhoNaRedejTextField;
    private javax.swing.JButton cancelarjButton;
    private javax.swing.JButton editarjButton;
    private javax.swing.JButton excluirjButton;
    private javax.swing.JTable gradepathjTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton limparjButton;
    private javax.swing.JLabel nomeArqRedejLabel;
    private javax.swing.JTextField nomeBasejTextField;
    private javax.swing.JButton novojButton;
    private javax.swing.JButton salvarjButton;
    private javax.swing.JTextField tabuladorjTextField;
    // End of variables declaration//GEN-END:variables
}
