/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package concatwfm;

import Classes.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luciano.benfica
 */
public class JFCadastroCelula extends javax.swing.JDialog {

    /**
     * Creates new form JFCadastroCelula
     */
    public JFCadastroCelula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        buscarjButton = new javax.swing.JButton();
        novojButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        editarjButton = new javax.swing.JButton();
        salvarjButton = new javax.swing.JButton();
        salvarMaisjButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        alterarjButton = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        cancelarjButton = new javax.swing.JButton();
        limparjButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        celulaIdjTextField = new javax.swing.JTextField();
        celulaNomejTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        operacaojComboBox = new javax.swing.JComboBox();
        cadastroOperacaojButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gradeCelulajTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        contadorRegistrosjLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setBackground(new java.awt.Color(155, 155, 155));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        buscarjButton.setBackground(new java.awt.Color(155, 155, 155));
        buscarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/buscar.png"))); // NOI18N
        buscarjButton.setText("Buscar");
        buscarjButton.setFocusable(false);
        buscarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buscarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(buscarjButton);

        novojButton.setBackground(new java.awt.Color(155, 155, 155));
        novojButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/new2.png"))); // NOI18N
        novojButton.setText("Novo");
        novojButton.setFocusable(false);
        novojButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        novojButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        novojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novojButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(novojButton);
        jToolBar1.add(jSeparator1);

        editarjButton.setBackground(new java.awt.Color(155, 155, 155));
        editarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/edit.png"))); // NOI18N
        editarjButton.setText("Editar");
        editarjButton.setFocusable(false);
        editarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(editarjButton);

        salvarjButton.setBackground(new java.awt.Color(155, 155, 155));
        salvarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/save.png"))); // NOI18N
        salvarjButton.setText("Salvar");
        salvarjButton.setFocusable(false);
        salvarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salvarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        salvarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(salvarjButton);

        salvarMaisjButton.setBackground(new java.awt.Color(155, 155, 155));
        salvarMaisjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/save_plus.png"))); // NOI18N
        salvarMaisjButton.setText("Salvar+");
        salvarMaisjButton.setFocusable(false);
        salvarMaisjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salvarMaisjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        salvarMaisjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarMaisjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(salvarMaisjButton);
        jToolBar1.add(jSeparator3);

        alterarjButton.setBackground(new java.awt.Color(155, 155, 155));
        alterarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/save2.png"))); // NOI18N
        alterarjButton.setText("Alterar");
        alterarjButton.setFocusable(false);
        alterarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        alterarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        alterarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(alterarjButton);
        jToolBar1.add(jSeparator4);
        jToolBar1.add(jSeparator5);
        jToolBar1.add(jSeparator6);

        cancelarjButton.setBackground(new java.awt.Color(155, 155, 155));
        cancelarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Cancel.png"))); // NOI18N
        cancelarjButton.setText("Cancelar");
        cancelarjButton.setFocusable(false);
        cancelarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancelarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(cancelarjButton);

        limparjButton.setBackground(new java.awt.Color(155, 155, 155));
        limparjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/clear.png"))); // NOI18N
        limparjButton.setText("Limpar");
        limparjButton.setFocusable(false);
        limparjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        limparjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        limparjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(limparjButton);

        jLabel1.setText("Cod. Celula");

        celulaIdjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                celulaIdjTextFieldKeyTyped(evt);
            }
        });

        jLabel2.setText("Nome célula");

        jLabel3.setText("Operação");

        cadastroOperacaojButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/add_small.png"))); // NOI18N
        cadastroOperacaojButton.setContentAreaFilled(false);
        cadastroOperacaojButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastroOperacaojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroOperacaojButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(celulaIdjTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(celulaNomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3)
                    .addComponent(operacaojComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cadastroOperacaojButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(celulaIdjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(celulaNomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(operacaojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastroOperacaojButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro célula", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        gradeCelulajTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod. Célula", "Célula", "Operação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gradeCelulajTable.getTableHeader().setReorderingAllowed(false);
        gradeCelulajTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gradeCelulajTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(gradeCelulajTable);
        gradeCelulajTable.getColumnModel().getColumn(0).setResizable(false);
        gradeCelulajTable.getColumnModel().getColumn(0).setPreferredWidth(10);
        gradeCelulajTable.getColumnModel().getColumn(1).setResizable(false);
        gradeCelulajTable.getColumnModel().getColumn(1).setPreferredWidth(150);
        gradeCelulajTable.getColumnModel().getColumn(2).setResizable(false);
        gradeCelulajTable.getColumnModel().getColumn(2).setPreferredWidth(50);

        jLabel4.setText("Total de registros:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contadorRegistrosjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(contadorRegistrosjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    ClassConecta conecta = new ClassConecta();
    
    private ComboItem combo_operacao;
    private int click_celula;
    
    public void getGrandeCelulas() throws ParseException {
        //Consultar Celulas
        CadastroCelulas oCadCel = new CadastroCelulas();

        ResultSet resultSet = null;

        String[] colunasTabela = new String[]{"Cod. Célula", "Célula", "Operação"};
        DefaultTableModel modeloTabela = new DefaultTableModel(null, colunasTabela) {

            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        gradeCelulajTable.setModel(modeloTabela);
        gradeCelulajTable.getColumnModel().getColumn(0).setPreferredWidth(10);
        gradeCelulajTable.getColumnModel().getColumn(1).setPreferredWidth(150);
        gradeCelulajTable.getColumnModel().getColumn(2).setPreferredWidth(50);

        try {

            resultSet = oCadCel.getConsultar();

            if (resultSet.getRow() == 1) {
                resultSet.first();
            }


        } catch (SQLException ex) {
            Logger.getLogger(Funcionarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {

            while (resultSet.next()) {

                modeloTabela.addRow(new String[]{
                            resultSet.getString("CELULA_ID"),
                            resultSet.getString("CELULA_NOME"),
                            resultSet.getString("OPERACAO_NAME")
                });

            }

        } catch (SQLException ex) {
            Logger.getLogger(JFCadastroCelula.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    public void getFieldCelula(int click_celula) throws ParseException {

        CadastroCelulas oCadCel = new CadastroCelulas();
        ResultSet rs;
        oCadCel.setCelula_id(click_celula);

        try {
            rs = oCadCel.getConsultar();
            rs.next();

            //Pegar campos
            ComboItem oItem = new ComboItem(rs.getInt(1), rs.getString(2));
            operacaojComboBox.setSelectedItem(oItem);
            
            celulaIdjTextField.setText(Integer.toString(rs.getInt("CELULA_ID")));
            celulaNomejTextField.setText(rs.getString("CELULA_NOME"));

        } catch (SQLException ex) {
            Logger.getLogger(Funcionarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void atualizaGrade(){
        try {
            getGrandeCelulas();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao atualizar grade.\n"+e, "Mensagem do sistema", JOptionPane.ERROR_MESSAGE);
        }
        
        int contador_registros = gradeCelulajTable.getRowCount();
        contadorRegistrosjLabel.setText(Integer.toString(contador_registros));
    }
    
    private void atualizarComboOperacao(){
        
        Operacoes oOperacoes = new Operacoes();
        
        ResultSet rs;
        
        try {
            
            rs = oOperacoes.getConsultarIdOperacao();
            operacaojComboBox.removeAllItems();
            while (rs.next()) {                
                
                operacaojComboBox.addItem(new ComboItem(rs.getInt(1), rs.getString(2)));
            }
            operacaojComboBox.updateUI();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao atualizar combo operações.\n"+e, 
                    "Mensagem do sistema", JOptionPane.ERROR_MESSAGE);
        } 
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        novojButton.setVisible(true);
        editarjButton.setVisible(false);
        salvarjButton.setVisible(false);
        salvarMaisjButton.setVisible(false);
        alterarjButton.setVisible(false);
        try {
            ClassConecta.conecta();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao abrir conexão com o banco de dados\n"+e, 
                    "Mensagem do istema", JOptionPane.ERROR_MESSAGE);
        }
        atualizarComboOperacao();
        atualizaGrade();
    }//GEN-LAST:event_formWindowOpened

    private void novojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novojButtonActionPerformed
        // TODO add your handling code here:
        novojButton.setVisible(false);
        editarjButton.setVisible(false);
        buscarjButton.setVisible(true);
        salvarjButton.setVisible(true);
        salvarMaisjButton.setVisible(true);
        cancelarjButton.setVisible(true);
        celulaIdjTextField.grabFocus();

        try {
            ClassConecta.con.setAutoCommit(false);
        } catch (Exception e) {
        }
        limparjButtonActionPerformed(evt);
    }//GEN-LAST:event_novojButtonActionPerformed

    private void limparjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparjButtonActionPerformed
        // TODO add your handling code here:
        celulaIdjTextField.setText("");
        celulaNomejTextField.setText("");
    }//GEN-LAST:event_limparjButtonActionPerformed

    private void salvarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarjButtonActionPerformed
        // TODO add your handling code here:
        CadastroCelulas oCadCel = new CadastroCelulas();
        
        if(celulaIdjTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "O campo Cod. Cel. é obrigatório.", "Mensgem do sistema", JOptionPane.WARNING_MESSAGE);
        }else if(celulaNomejTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "O campo Nome Célula. é obrigatório.", "Mensgem do sistema", JOptionPane.WARNING_MESSAGE);
        }else if(operacaojComboBox.getSelectedItem().equals("")){
            JOptionPane.showMessageDialog(null, "O campo OPERAÇÃO é obrigatório.", "Mensgem do sistema", JOptionPane.WARNING_MESSAGE);
        }else{
            
            try {

                salvarjButton.setVisible(false);
                novojButton.setVisible(true);
                editarjButton.setVisible(false);
                cancelarjButton.setVisible(false);
                
                combo_operacao = (ComboItem)operacaojComboBox.getSelectedItem();
                
                oCadCel.setCelula_id(Integer.parseInt(celulaIdjTextField.getText().trim()));
                oCadCel.setOperacao_id(combo_operacao.getId());
                oCadCel.setCelula_nome(celulaNomejTextField.getText().trim().toUpperCase());
                oCadCel.setCadastrar();                
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar\n"+e, "Mensgem do sistema", JOptionPane.ERROR_MESSAGE);                
            }
        }
        
        atualizaGrade();
        
    }//GEN-LAST:event_salvarjButtonActionPerformed

    private void celulaIdjTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_celulaIdjTextFieldKeyTyped
        // TODO add your handling code here:
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_celulaIdjTextFieldKeyTyped

    private void gradeCelulajTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradeCelulajTableMouseClicked
        // TODO add your handling code here:
        editarjButton.setVisible(true);

        click_celula = Integer.parseInt(gradeCelulajTable.getValueAt(gradeCelulajTable.getSelectedRow(), 0).toString());
        try {
            getFieldCelula(click_celula);
        } catch (ParseException ex) {
            Logger.getLogger(JFCadastroCelula.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_gradeCelulajTableMouseClicked

    private void salvarMaisjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarMaisjButtonActionPerformed
        // TODO add your handling code here:
        salvarjButtonActionPerformed(evt);
        novojButtonActionPerformed(evt);
    }//GEN-LAST:event_salvarMaisjButtonActionPerformed

    private void editarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarjButtonActionPerformed
        // TODO add your handling code here:
        novojButton.setVisible(false);
        salvarjButton.setVisible(false);
        editarjButton.setVisible(false);
        alterarjButton.setVisible(true);
        cancelarjButton.setVisible(true);
        try {
            ClassConecta.con.setAutoCommit(false);
        } catch (SQLException ex) {
            Logger.getLogger(Funcionarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editarjButtonActionPerformed

    private void alterarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarjButtonActionPerformed
        // TODO add your handling code here:
        CadastroCelulas oCadCel = new CadastroCelulas();
        
        if(celulaIdjTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "O campo Cod. Cel. é obrigatório.", "Mensgem do sistema", JOptionPane.WARNING_MESSAGE);
        }else if(celulaNomejTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "O campo Nome Célula. é obrigatório.", "Mensgem do sistema", JOptionPane.WARNING_MESSAGE);
        }else if(operacaojComboBox.getSelectedItem().equals("")){
            JOptionPane.showMessageDialog(null, "O campo OPERAÇÃO é obrigatório.", "Mensgem do sistema", JOptionPane.WARNING_MESSAGE);
        }else{
            
            try {

                salvarjButton.setVisible(false);
                novojButton.setVisible(true);
                editarjButton.setVisible(false);
                cancelarjButton.setVisible(false);
                
                oCadCel.setCod_celula_update(click_celula);
                combo_operacao = (ComboItem)operacaojComboBox.getSelectedItem();
                
                oCadCel.setCelula_id(Integer.parseInt(celulaIdjTextField.getText().trim()));
                oCadCel.setOperacao_id(combo_operacao.getId());
                oCadCel.setCelula_nome(celulaNomejTextField.getText().trim().toUpperCase());
                oCadCel.setAlterar(conecta);                
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao atualizar registro.\n"+e, "Mensgem do sistema", JOptionPane.ERROR_MESSAGE);                
            }
        }
        
        atualizaGrade();
        
    }//GEN-LAST:event_alterarjButtonActionPerformed

    private void cadastroOperacaojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroOperacaojButtonActionPerformed
        // TODO add your handling code here:
        jFOperacao oFormCadOper = new jFOperacao();
        
        oFormCadOper.setTitle("Cadastro de operações.");
        oFormCadOper.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        oFormCadOper.setLocationRelativeTo(null);
        oFormCadOper.setModal(true);
        oFormCadOper.pack();
        oFormCadOper.setVisible(true);
        
        atualizarComboOperacao();
        
    }//GEN-LAST:event_cadastroOperacaojButtonActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFCadastroCelula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFCadastroCelula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFCadastroCelula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCadastroCelula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new JFCadastroCelula().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarjButton;
    private javax.swing.JButton buscarjButton;
    private javax.swing.JButton cadastroOperacaojButton;
    private javax.swing.JButton cancelarjButton;
    private javax.swing.JTextField celulaIdjTextField;
    private javax.swing.JTextField celulaNomejTextField;
    private javax.swing.JLabel contadorRegistrosjLabel;
    private javax.swing.JButton editarjButton;
    private javax.swing.JTable gradeCelulajTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton limparjButton;
    private javax.swing.JButton novojButton;
    private javax.swing.JComboBox operacaojComboBox;
    private javax.swing.JButton salvarMaisjButton;
    private javax.swing.JButton salvarjButton;
    // End of variables declaration//GEN-END:variables
}
