/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package concatwfm;

import Classes.ClassConecta;
import Classes.Funcionarios;
import Classes.Funcoes;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luciano.benfica
 */
public class JFFuncionarios extends javax.swing.JFrame {

    /**
     * Creates new form JFFuncionarios
     */
    public JFFuncionarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        buscarjButton = new javax.swing.JButton();
        novojButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        editarjButton = new javax.swing.JButton();
        salvarjButton = new javax.swing.JButton();
        salvarMaisjButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        alterarjButton = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        cancelarjButton = new javax.swing.JButton();
        limparjButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gradeFuncionariojTable = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        matriculajTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        gmidjTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        niceIDjTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        loginAvayajTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nomejTextField = new javax.swing.JTextField();
        hiredatejFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        networkjTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        emailjTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        statusjButton = new javax.swing.JButton();
        cargosjButton = new javax.swing.JButton();
        celulajButton = new javax.swing.JButton();
        hierarquiajButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        ccmsjTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        gminjTextField = new javax.swing.JTextField();
        idSpreadFastTextField2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setBackground(new java.awt.Color(155, 155, 155));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        buscarjButton.setBackground(new java.awt.Color(155, 155, 155));
        buscarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/buscar.png"))); // NOI18N
        buscarjButton.setText("Buscar");
        buscarjButton.setFocusable(false);
        buscarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buscarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buscarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(buscarjButton);

        novojButton.setBackground(new java.awt.Color(155, 155, 155));
        novojButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/new2.png"))); // NOI18N
        novojButton.setText("Novo");
        novojButton.setFocusable(false);
        novojButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        novojButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        novojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novojButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(novojButton);
        jToolBar1.add(jSeparator1);

        editarjButton.setBackground(new java.awt.Color(155, 155, 155));
        editarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/edit.png"))); // NOI18N
        editarjButton.setText("Editar");
        editarjButton.setFocusable(false);
        editarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(editarjButton);

        salvarjButton.setBackground(new java.awt.Color(155, 155, 155));
        salvarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/save.png"))); // NOI18N
        salvarjButton.setText("Salvar");
        salvarjButton.setFocusable(false);
        salvarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salvarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        salvarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(salvarjButton);

        salvarMaisjButton.setBackground(new java.awt.Color(155, 155, 155));
        salvarMaisjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/save_plus.png"))); // NOI18N
        salvarMaisjButton.setText("Salvar+");
        salvarMaisjButton.setFocusable(false);
        salvarMaisjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salvarMaisjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        salvarMaisjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarMaisjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(salvarMaisjButton);
        jToolBar1.add(jSeparator3);

        alterarjButton.setBackground(new java.awt.Color(155, 155, 155));
        alterarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/save2.png"))); // NOI18N
        alterarjButton.setText("Alterar");
        alterarjButton.setFocusable(false);
        alterarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        alterarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        alterarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(alterarjButton);
        jToolBar1.add(jSeparator4);
        jToolBar1.add(jSeparator5);
        jToolBar1.add(jSeparator6);

        cancelarjButton.setBackground(new java.awt.Color(155, 155, 155));
        cancelarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Cancel.png"))); // NOI18N
        cancelarjButton.setText("Cancelar");
        cancelarjButton.setFocusable(false);
        cancelarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancelarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cancelarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(cancelarjButton);

        limparjButton.setBackground(new java.awt.Color(155, 155, 155));
        limparjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/clear.png"))); // NOI18N
        limparjButton.setText("Limpar");
        limparjButton.setFocusable(false);
        limparjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        limparjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        limparjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(limparjButton);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        gradeFuncionariojTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matrícula", "Nome funcionário", "Login de rede TP", "GMID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gradeFuncionariojTable.getTableHeader().setReorderingAllowed(false);
        gradeFuncionariojTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gradeFuncionariojTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(gradeFuncionariojTable);
        gradeFuncionariojTable.getColumnModel().getColumn(0).setResizable(false);
        gradeFuncionariojTable.getColumnModel().getColumn(0).setPreferredWidth(10);
        gradeFuncionariojTable.getColumnModel().getColumn(1).setResizable(false);
        gradeFuncionariojTable.getColumnModel().getColumn(1).setPreferredWidth(250);
        gradeFuncionariojTable.getColumnModel().getColumn(2).setResizable(false);
        gradeFuncionariojTable.getColumnModel().getColumn(2).setPreferredWidth(10);
        gradeFuncionariojTable.getColumnModel().getColumn(3).setResizable(false);
        gradeFuncionariojTable.getColumnModel().getColumn(3).setPreferredWidth(10);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 833, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        matriculajTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                matriculajTextFieldKeyReleased(evt);
            }
        });

        jLabel1.setText("Matrícula");

        gmidjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gmidjTextFieldKeyReleased(evt);
            }
        });

        jLabel2.setText("GMID");

        jLabel3.setText("NiceID");

        loginAvayajTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                loginAvayajTextFieldKeyTyped(evt);
            }
        });

        jLabel4.setText("Login avaya");

        jLabel5.setText("Nome");

        nomejTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomejTextFieldKeyReleased(evt);
            }
        });

        try {
            hiredatejFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setText("Data admissão");

        jLabel7.setText("login de rede TP");

        jLabel8.setText("E-mail");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Movimentações", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 204)));

        statusjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/concluido.png"))); // NOI18N
        statusjButton.setText("Status");
        statusjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusjButtonActionPerformed(evt);
            }
        });

        cargosjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/cargos.png"))); // NOI18N
        cargosjButton.setText("Cargos");
        cargosjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargosjButtonActionPerformed(evt);
            }
        });

        celulajButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/celulas.png"))); // NOI18N
        celulajButton.setText("Células");
        celulajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celulajButtonActionPerformed(evt);
            }
        });

        hierarquiajButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/hierarchi.png"))); // NOI18N
        hierarquiajButton.setText("Hieararquia");
        hierarquiajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hierarquiajButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(statusjButton, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(celulajButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cargosjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hierarquiajButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusjButton)
                    .addComponent(cargosjButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(celulajButton)
                    .addComponent(hierarquiajButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setText("CCMS");

        ccmsjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ccmsjTextFieldKeyTyped(evt);
            }
        });

        jLabel10.setText("GMIN");

        gminjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gminjTextFieldKeyTyped(evt);
            }
        });

        jLabel11.setText("ID SpreadFast");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(hiredatejFormattedTextField)))
                    .addComponent(jLabel8)
                    .addComponent(emailjTextField)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(matriculajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gmidjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel10)))
                            .addComponent(jLabel9)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ccmsjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(gminjTextField)))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(niceIDjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(loginAvayajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(networkjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(idSpreadFastTextField2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hiredatejFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(matriculajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gmidjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(niceIDjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginAvayajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(networkjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ccmsjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gminjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idSpreadFastTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 33, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cadastro funcionários", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    ClassConecta conecta = new ClassConecta();
    int operador = -1;
    int click_matricula;

    public void getGrandeFuncionarios() throws ParseException {
        //Consultar pedidos
        Funcionarios oFunc = new Funcionarios();

        if (nomejTextField.getText().length() > 0) {
            oFunc.setNome(nomejTextField.getText() + "%");
        }
        if (gmidjTextField.getText().length() > 0) {
            oFunc.setGmid(gmidjTextField.getText() + "%");
        }
        if (matriculajTextField.getText().length() != 0) {

            oFunc.setMatricula(Integer.valueOf(matriculajTextField.getText()));
        }

        ResultSet resultSet = null;

        String[] colunasTabela = new String[]{"Matrícula", "Nome funcionário", "Login de rede TP", "GMID"};
        DefaultTableModel modeloTabela = new DefaultTableModel(null, colunasTabela) {

            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        gradeFuncionariojTable.setModel(modeloTabela);
        gradeFuncionariojTable.getColumnModel().getColumn(0).setPreferredWidth(10);
        gradeFuncionariojTable.getColumnModel().getColumn(1).setPreferredWidth(250);
        gradeFuncionariojTable.getColumnModel().getColumn(2).setPreferredWidth(10);
        gradeFuncionariojTable.getColumnModel().getColumn(3).setPreferredWidth(10);

        try {

            resultSet = oFunc.getConsultar();

            if (resultSet.getRow() == 1) {
                resultSet.first();
            }


        } catch (SQLException ex) {
            Logger.getLogger(Funcionarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {

            while (resultSet.next()) {

                modeloTabela.addRow(new String[]{
                            resultSet.getString("MATRICULA"),
                            resultSet.getString("NOME"),
                            resultSet.getString("NETWORK"),
                            resultSet.getString("GMID"),});

            }

        } catch (SQLException ex) {
            Logger.getLogger(Funcionarios.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void getFieldFuncionario(int click_matricula) throws ParseException {

        Funcionarios oFunc = new Funcionarios();
        ResultSet rs;
        oFunc.setMatricula(click_matricula);

        try {
            rs = oFunc.getConsultar();
            rs.next();

            //Pegar campos
            nomejTextField.setText(rs.getString("NOME"));
            hiredatejFormattedTextField.setText(Funcoes.getDataFormat(rs.getDate("HIREDATE")));
            matriculajTextField.setText(Integer.toString(rs.getInt("MATRICULA")));
            gmidjTextField.setText(rs.getString("GMID"));
            niceIDjTextField.setText(rs.getString("NICEID"));
            loginAvayajTextField.setText(Integer.toString(rs.getInt("LOGIN_AVAYA")));
            networkjTextField.setText(rs.getString("NETWORK"));
            emailjTextField.setText(rs.getString("EMAIL"));
            ccmsjTextField.setText(Integer.toString(rs.getInt("IDCCMS")));
            idSpreadFastTextField2.setText(rs.getString("ID_SPREADFAST"));
            gminjTextField.setText(Integer.toString(rs.getInt("GMIN")));

        } catch (SQLException ex) {
            Logger.getLogger(Funcionarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void verificaCamposVazios() {


        if (matriculajTextField.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "O campo MATRÍCULA é obrigatório", "Mensagem do sistema", JOptionPane.WARNING_MESSAGE);
            matriculajTextField.grabFocus();
            operador = -1;

        } else if (nomejTextField.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "O campo NOME é obrigatório", "Mensagem do sistema", JOptionPane.WARNING_MESSAGE);
            nomejTextField.grabFocus();
            operador = -1;

        } else if (hiredatejFormattedTextField.getText().equals("  /  /    ")) {

            JOptionPane.showMessageDialog(null, "O campo DATA ADMISSÃO é obrigatório", "Mensagem do sistema", JOptionPane.WARNING_MESSAGE);
            hiredatejFormattedTextField.grabFocus();
            operador = -1;

        } else {

            operador = 1;
        }

    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        novojButton.setVisible(true);
        editarjButton.setVisible(false);
        salvarjButton.setVisible(false);
        salvarMaisjButton.setVisible(false);
        alterarjButton.setVisible(false);

        statusjButton.setEnabled(false);
        cargosjButton.setEnabled(false);
        celulajButton.setEnabled(false);
        hierarquiajButton.setEnabled(false);

        try {
            ClassConecta.conecta();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao abrir conexão com o banco de dados.\n" + e,
                    "Mensagem do sistema", JOptionPane.ERROR_MESSAGE);
        }

        buscarjButtonActionPerformed(null);
    }//GEN-LAST:event_formWindowOpened

    private void novojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novojButtonActionPerformed
        // TODO add your handling code here:
        novojButton.setVisible(false);
        editarjButton.setVisible(false);
        buscarjButton.setVisible(true);
        salvarjButton.setVisible(true);
        salvarMaisjButton.setVisible(true);
        cancelarjButton.setVisible(true);
        nomejTextField.grabFocus();

        try {
            ClassConecta.con.setAutoCommit(false);
        } catch (Exception e) {
        }
        limparjButtonActionPerformed(evt);
    }//GEN-LAST:event_novojButtonActionPerformed

    private void salvarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarjButtonActionPerformed
        // TODO add your handling code here:
        Funcionarios oFunc = new Funcionarios();

        verificaCamposVazios();

        if (operador == 1) {

            try {

                salvarjButton.setVisible(false);
                novojButton.setVisible(true);
                editarjButton.setVisible(false);
                cancelarjButton.setVisible(false);

                Integer idccms;
                Integer gmin;

                if (ccmsjTextField.getText().isEmpty()) {
                    idccms = null;
                } else {
                    idccms = Integer.parseInt(ccmsjTextField.getText().trim());
                }
                if (gminjTextField.getText().isEmpty()) {
                    gmin = null;
                } else {
                    gmin = Integer.parseInt(gminjTextField.getText().trim());
                }

                oFunc.setMatricula(Integer.parseInt(matriculajTextField.getText().trim()));
                oFunc.setGmid(gmidjTextField.getText().trim().toUpperCase());
                oFunc.setNiceID(niceIDjTextField.getText().trim());

                if (loginAvayajTextField.getText().isEmpty()) {
                    oFunc.setLogin_avaya(0);
                } else {
                    oFunc.setLogin_avaya(Integer.parseInt(loginAvayajTextField.getText().trim()));
                }

                oFunc.setNome(nomejTextField.getText().trim().toUpperCase());
                oFunc.setHiredate(Funcoes.getDataFormatBR(hiredatejFormattedTextField.getText()));
                oFunc.setNetwork(networkjTextField.getText().trim().toUpperCase());
                oFunc.setEmail(emailjTextField.getText().trim().toLowerCase());
                oFunc.setIdccms(idccms);
                oFunc.setId_spreadfast(idSpreadFastTextField2.getText().trim().toUpperCase());
                oFunc.setGmin(gmin);
                oFunc.setCadastrar();

            } catch (NumberFormatException | ParseException e) {
                JOptionPane.showMessageDialog(null, "Erro ao salvar o registro.\n" + e,
                        "Mensagem do sistema", JOptionPane.ERROR_MESSAGE);
            }

        }

        buscarjButtonActionPerformed(evt);

    }//GEN-LAST:event_salvarjButtonActionPerformed

    private void loginAvayajTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginAvayajTextFieldKeyTyped
        // bloqueia a entrada de caracteres alfabeticos.
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_loginAvayajTextFieldKeyTyped

    private void buscarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarjButtonActionPerformed
        // TODO add your handling code here:
        try {
            getGrandeFuncionarios();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar a grade funcionários.\n" + e, "Mensagem do sistema", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buscarjButtonActionPerformed

    private void gradeFuncionariojTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradeFuncionariojTableMouseClicked
        // TODO add your handling code here:
        editarjButton.setVisible(true);
        statusjButton.setEnabled(true);
        cargosjButton.setEnabled(true);
        celulajButton.setEnabled(true);
        hierarquiajButton.setEnabled(true);

        click_matricula = Integer.parseInt(gradeFuncionariojTable.getValueAt(gradeFuncionariojTable.getSelectedRow(), 0).toString());
        try {
            getFieldFuncionario(click_matricula);
        } catch (ParseException ex) {
            Logger.getLogger(Funcionarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_gradeFuncionariojTableMouseClicked

    private void salvarMaisjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarMaisjButtonActionPerformed
        // TODO add your handling code here:

        salvarjButtonActionPerformed(evt);
        novojButtonActionPerformed(evt);
    }//GEN-LAST:event_salvarMaisjButtonActionPerformed

    private void cancelarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarjButtonActionPerformed
        // TODO add your handling code here:
        novojButton.setVisible(true);
        editarjButton.setVisible(false);
        salvarjButton.setVisible(false);
        salvarMaisjButton.setVisible(false);
        alterarjButton.setVisible(false);
        cancelarjButton.setVisible(false);

        try {
            ClassConecta.con.setAutoCommit(false);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cancelarjButtonActionPerformed

    private void editarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarjButtonActionPerformed
        // TODO add your handling code here:
        novojButton.setVisible(false);
        salvarjButton.setVisible(false);
        editarjButton.setVisible(false);
        alterarjButton.setVisible(true);
        cancelarjButton.setVisible(true);
        try {
            ClassConecta.con.setAutoCommit(false);
        } catch (SQLException ex) {
            Logger.getLogger(Funcionarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editarjButtonActionPerformed

    private void nomejTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomejTextFieldKeyReleased
        // TODO add your handling code here:
        if (!alterarjButton.isVisible()) {
            try {
                Funcionarios oFunc = new Funcionarios();
                oFunc.setNome(nomejTextField.getText());
                ResultSet rs = null;
                rs = oFunc.getConsultar();
                getGrandeFuncionarios();
            } catch (ParseException | SQLException ex) {
                Logger.getLogger(JFFuncionarios.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        if ("".equals(nomejTextField.getText())) {
            limparjButtonActionPerformed(null);
        }
    }//GEN-LAST:event_nomejTextFieldKeyReleased

    private void gmidjTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gmidjTextFieldKeyReleased
        // TODO add your handling code here:
        if (!alterarjButton.isVisible()) {
            try {
                Funcionarios oFunc = new Funcionarios();
                oFunc.setGmid(gmidjTextField.getText());
                ResultSet rs = null;
                rs = oFunc.getConsultar();
                getGrandeFuncionarios();
            } catch (ParseException | SQLException ex) {
                Logger.getLogger(JFFuncionarios.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_gmidjTextFieldKeyReleased

    private void limparjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparjButtonActionPerformed
        // TODO add your handling code here:
        nomejTextField.setText("");
        hiredatejFormattedTextField.setText("");
        gmidjTextField.setText("");
        matriculajTextField.setText("");
        niceIDjTextField.setText("");
        loginAvayajTextField.setText("");
        networkjTextField.setText("");
        emailjTextField.setText("");
        ccmsjTextField.setText("");
        idSpreadFastTextField2.setText("");
        gminjTextField.setText("");
    }//GEN-LAST:event_limparjButtonActionPerformed

    private void alterarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarjButtonActionPerformed
        // TODO add your handling code here:
        Funcionarios oFunc = new Funcionarios();

        int verifica_matricula = Integer.parseInt(matriculajTextField.getText().trim());
        verificaCamposVazios();

        if (click_matricula != verifica_matricula) {
            JOptionPane.showMessageDialog(null, "Atenção!\n"
                    + "A matrícula não pode ser alterada, em caso de erro de cadastro, contate os administradores do sistema.",
                    "Mensagem do sistema", JOptionPane.WARNING_MESSAGE);
        } else {

            if (operador == 1) {

                try {

                    salvarjButton.setVisible(false);
                    novojButton.setVisible(true);
                    editarjButton.setVisible(false);
                    cancelarjButton.setVisible(false);
                    alterarjButton.setVisible(false);
                    salvarMaisjButton.setVisible(false);
                    
                    
                    Integer idccms;
                    Integer gmin;
                    
                    if (ccmsjTextField.getText().isEmpty()) {
                        idccms = null;
                    }else{
                        idccms = Integer.parseInt(ccmsjTextField.getText().trim());
                    }
                    if (gminjTextField.getText().isEmpty()) {
                        gmin = null;
                    }else{
                        gmin = Integer.parseInt(gminjTextField.getText().trim());
                    }

                    oFunc.setAltera_matricula(click_matricula);


                    oFunc.setGmid(gmidjTextField.getText().trim().toUpperCase());
                    oFunc.setNiceID(niceIDjTextField.getText().trim());

                    if (loginAvayajTextField.getText().isEmpty()) {
                        oFunc.setLogin_avaya(0);
                    } else {
                        oFunc.setLogin_avaya(Integer.parseInt(loginAvayajTextField.getText().trim()));
                    }
                    oFunc.setMatricula(Integer.parseInt(matriculajTextField.getText().trim()));
                    oFunc.setNome(nomejTextField.getText().trim().toUpperCase());
                    oFunc.setHiredate(Funcoes.getDataFormatBR(hiredatejFormattedTextField.getText()));
                    oFunc.setNetwork(networkjTextField.getText().trim().toUpperCase());
                    oFunc.setEmail(emailjTextField.getText().trim().toLowerCase());
                    oFunc.setIdccms(idccms);
                    oFunc.setId_spreadfast(idSpreadFastTextField2.getText().trim().toUpperCase());
                    oFunc.setGmin(gmin);
                    oFunc.setAlterar(conecta);

                } catch (NumberFormatException | ParseException e) {
                    JOptionPane.showMessageDialog(null, "Erro ao salvar o registro.\n" + e,
                            "Mensagem do sistema", JOptionPane.ERROR_MESSAGE);
                }

            }
        }

        buscarjButtonActionPerformed(evt);
    }//GEN-LAST:event_alterarjButtonActionPerformed

    private void statusjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusjButtonActionPerformed
        // TODO add your handling code here:
        jFFuncionarioStatus oFormFunStatus = new jFFuncionarioStatus();

        oFormFunStatus.recebe_matricula = Integer.parseInt(matriculajTextField.getText());
        oFormFunStatus.recebe_nome = nomejTextField.getText().trim().toUpperCase();

        oFormFunStatus.setTitle("Alterar Status");
        oFormFunStatus.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        oFormFunStatus.setLocationRelativeTo(null);
        oFormFunStatus.setModal(true);
        oFormFunStatus.pack();
        oFormFunStatus.setVisible(true);

        editarjButton.setVisible(false);
        statusjButton.setEnabled(false);
        cargosjButton.setEnabled(false);
        celulajButton.setEnabled(false);
        hierarquiajButton.setEnabled(false);
    }//GEN-LAST:event_statusjButtonActionPerformed

    private void cargosjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargosjButtonActionPerformed
        // TODO add your handling code here:
        JFFuncionariosCargos oFormFunCarg = new JFFuncionariosCargos();

        oFormFunCarg.recebe_matricula = Integer.parseInt(matriculajTextField.getText());
        oFormFunCarg.recebe_nome = nomejTextField.getText().trim().toUpperCase();

        oFormFunCarg.setTitle("Alterar Status");
        oFormFunCarg.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        oFormFunCarg.setLocationRelativeTo(null);
        oFormFunCarg.setModal(true);
        oFormFunCarg.pack();
        oFormFunCarg.setVisible(true);

        editarjButton.setVisible(false);
        statusjButton.setEnabled(false);
        cargosjButton.setEnabled(false);
        celulajButton.setEnabled(false);
        hierarquiajButton.setEnabled(false);
    }//GEN-LAST:event_cargosjButtonActionPerformed

    private void celulajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celulajButtonActionPerformed
        // TODO add your handling code here:
        JFFuncionariosCelulas oFormFunCel = new JFFuncionariosCelulas();

        oFormFunCel.recebe_matricula = Integer.parseInt(matriculajTextField.getText());
        oFormFunCel.recebe_nome = nomejTextField.getText().trim().toUpperCase();

        oFormFunCel.setTitle("Alterar célula");
        oFormFunCel.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        oFormFunCel.setLocationRelativeTo(null);
        oFormFunCel.setModal(true);
        oFormFunCel.pack();
        oFormFunCel.setVisible(true);

        editarjButton.setVisible(false);
        statusjButton.setEnabled(false);
        cargosjButton.setEnabled(false);
        celulajButton.setEnabled(false);
        hierarquiajButton.setEnabled(false);
    }//GEN-LAST:event_celulajButtonActionPerformed

    private void hierarquiajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hierarquiajButtonActionPerformed
        // TODO add your handling code here:
        JFHierarquia oFormHier = new JFHierarquia();

        oFormHier.recebe_matricula = Integer.parseInt(matriculajTextField.getText());
        oFormHier.recebe_nome = nomejTextField.getText().trim().toUpperCase();

        oFormHier.setTitle("Cadastro Hierarquia");
        oFormHier.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        oFormHier.setLocationRelativeTo(null);
        oFormHier.setModal(true);
        oFormHier.pack();
        oFormHier.setVisible(true);

        editarjButton.setVisible(false);
        statusjButton.setEnabled(false);
        cargosjButton.setEnabled(false);
        celulajButton.setEnabled(false);
        hierarquiajButton.setEnabled(false);
    }//GEN-LAST:event_hierarquiajButtonActionPerformed

    private void matriculajTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_matriculajTextFieldKeyReleased
        // TODO add your handling code here:
        String caracteres = matriculajTextField.getText().trim();
        int qtd_caracteres = caracteres.length();

        if (qtd_caracteres >= 9) {
            JOptionPane.showMessageDialog(null, "Atenção!\n"
                    + "O campo matrícula não pode ter mais que 9 caracteres.",
                    "Mensagem do sistema", JOptionPane.WARNING_MESSAGE);

            caracteres = caracteres.substring(0, caracteres.length() - 1);
            matriculajTextField.setText("");
            matriculajTextField.setText(caracteres);

        } else {

            if (!"".equals(matriculajTextField.getText().trim())) {
                try {
                    Funcionarios oFunc = new Funcionarios();
                    oFunc.setMatricula(Integer.parseInt(matriculajTextField.getText()));
                    ResultSet rs = null;
                    rs = oFunc.getConsultar();
                    getGrandeFuncionarios();
                } catch (ParseException | SQLException ex) {
                    Logger.getLogger(JFFuncionarios.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                buscarjButtonActionPerformed(null);
            }
        }
    }//GEN-LAST:event_matriculajTextFieldKeyReleased

    private void ccmsjTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ccmsjTextFieldKeyTyped
        // TODO add your handling code here:
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_ccmsjTextFieldKeyTyped

    private void gminjTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gminjTextFieldKeyTyped
        // TODO add your handling code here:
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_gminjTextFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
                }
                new JFFuncionarios().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarjButton;
    private javax.swing.JButton buscarjButton;
    private javax.swing.JButton cancelarjButton;
    private javax.swing.JButton cargosjButton;
    private javax.swing.JTextField ccmsjTextField;
    private javax.swing.JButton celulajButton;
    private javax.swing.JButton editarjButton;
    private javax.swing.JTextField emailjTextField;
    private javax.swing.JTextField gmidjTextField;
    private javax.swing.JTextField gminjTextField;
    private javax.swing.JTable gradeFuncionariojTable;
    private javax.swing.JButton hierarquiajButton;
    private javax.swing.JFormattedTextField hiredatejFormattedTextField;
    private javax.swing.JTextField idSpreadFastTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton limparjButton;
    private javax.swing.JTextField loginAvayajTextField;
    private javax.swing.JTextField matriculajTextField;
    private javax.swing.JTextField networkjTextField;
    private javax.swing.JTextField niceIDjTextField;
    private javax.swing.JTextField nomejTextField;
    private javax.swing.JButton novojButton;
    private javax.swing.JButton salvarMaisjButton;
    private javax.swing.JButton salvarjButton;
    private javax.swing.JButton statusjButton;
    // End of variables declaration//GEN-END:variables
}
