/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package concatwfm;

import Controler.ControladorExcel;
import Modelo.ModeloExcel;
import VO.VistaExcel;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author luciano.benfica
 */
public class JFHome extends javax.swing.JFrame {

    /**
     * Creates new form JFHome
     */
    public JFHome() {
        initComponents();

        URL url = this.getClass().getResource("/Resources/if_Settings_1493289.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        setIconImage(iconeTitulo);

        this.setExtendedState(MAXIMIZED_BOTH);

        ActionListener tarefa = (new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                HORAS();
            }
        });
        javax.swing.Timer time = new javax.swing.Timer(1000, tarefa);
        time.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        funcionariosjButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        cadastroStatusjButton = new javax.swing.JButton();
        cadastroCargosjButton = new javax.swing.JButton();
        jButtoncadastroCelulas = new javax.swing.JButton();
        cadastroOperacoesjButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        fmajButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        horajLabel = new javax.swing.JLabel();
        usuarioLogadojLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArquivojMenu = new javax.swing.JMenu();
        sairDoSistemajMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        cadastroStatusjMenuItem = new javax.swing.JMenuItem();
        cadastroCargosjMenuItem = new javax.swing.JMenuItem();
        cadastroCelulajMenuItem = new javax.swing.JMenuItem();
        cadastroOperacoesjMenuItem = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        funcionariosjMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setBackground(new java.awt.Color(155, 155, 155));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator1);

        funcionariosjButton.setBackground(new java.awt.Color(155, 155, 155));
        funcionariosjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/user.png"))); // NOI18N
        funcionariosjButton.setText("Funcionários");
        funcionariosjButton.setFocusable(false);
        funcionariosjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        funcionariosjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        funcionariosjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionariosjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(funcionariosjButton);
        jToolBar1.add(jSeparator2);

        cadastroStatusjButton.setBackground(new java.awt.Color(155, 155, 155));
        cadastroStatusjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/concluido.png"))); // NOI18N
        cadastroStatusjButton.setText("Cadastro Status");
        cadastroStatusjButton.setFocusable(false);
        cadastroStatusjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cadastroStatusjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cadastroStatusjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroStatusjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(cadastroStatusjButton);

        cadastroCargosjButton.setBackground(new java.awt.Color(155, 155, 155));
        cadastroCargosjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/cargos.png"))); // NOI18N
        cadastroCargosjButton.setText("Cadastro Cargos");
        cadastroCargosjButton.setFocusable(false);
        cadastroCargosjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cadastroCargosjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cadastroCargosjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroCargosjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(cadastroCargosjButton);

        jButtoncadastroCelulas.setBackground(new java.awt.Color(155, 155, 155));
        jButtoncadastroCelulas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/celulas.png"))); // NOI18N
        jButtoncadastroCelulas.setText("Cadastro Células");
        jButtoncadastroCelulas.setFocusable(false);
        jButtoncadastroCelulas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtoncadastroCelulas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtoncadastroCelulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncadastroCelulasActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtoncadastroCelulas);

        cadastroOperacoesjButton.setBackground(new java.awt.Color(155, 155, 155));
        cadastroOperacoesjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/hierarchi.png"))); // NOI18N
        cadastroOperacoesjButton.setText("Cadastro Operações");
        cadastroOperacoesjButton.setFocusable(false);
        cadastroOperacoesjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cadastroOperacoesjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cadastroOperacoesjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroOperacoesjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(cadastroOperacoesjButton);
        jToolBar1.add(jSeparator3);

        fmajButton.setBackground(new java.awt.Color(155, 155, 155));
        fmajButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/excel_16_16.png"))); // NOI18N
        fmajButton.setText("FMA");
        fmajButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fmajButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        fmajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fmajButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(fmajButton);

        jButton1.setBackground(new java.awt.Color(155, 155, 155));
        jButton1.setText("MOP");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(usuarioLogadojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(horajLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(horajLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(usuarioLogadojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        menuArquivojMenu.setText("Arquivo");

        sairDoSistemajMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        sairDoSistemajMenuItem.setText("Sair do sistema");
        sairDoSistemajMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairDoSistemajMenuItemActionPerformed(evt);
            }
        });
        menuArquivojMenu.add(sairDoSistemajMenuItem);

        jMenuBar1.add(menuArquivojMenu);

        jMenu1.setText("Gerenciamento MOP");

        jMenu3.setText("Cadastros");

        cadastroStatusjMenuItem.setText("Cadastro Status");
        cadastroStatusjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroStatusjMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(cadastroStatusjMenuItem);

        cadastroCargosjMenuItem.setText("Cadastro de Cargos");
        cadastroCargosjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroCargosjMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(cadastroCargosjMenuItem);

        cadastroCelulajMenuItem.setText("Cadastro de Células");
        cadastroCelulajMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroCelulajMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(cadastroCelulajMenuItem);

        cadastroOperacoesjMenuItem.setText("Cadastro Operações");
        cadastroOperacoesjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroOperacoesjMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(cadastroOperacoesjMenuItem);

        jMenu1.add(jMenu3);

        jMenu4.setText("Gerenciamento");

        funcionariosjMenuItem.setText("Funcionários");
        funcionariosjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionariosjMenuItemActionPerformed(evt);
            }
        });
        jMenu4.add(funcionariosjMenuItem);

        jMenu1.add(jMenu4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1032, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 529, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int hh, mm, ss, h;
    Calendar CalendarHora;
    DecimalFormat formato;

    private void HORAS() {
        CalendarHora = Calendar.getInstance();
        hh = CalendarHora.get(Calendar.HOUR_OF_DAY);
        mm = CalendarHora.get(Calendar.MINUTE);
        ss = CalendarHora.get(Calendar.SECOND);
        formato = new DecimalFormat("00");
        horajLabel.setText("Hora: " + formatar(hh) + ":" + formatar(mm) + ":" + formatar(ss));
//horajLabel.setText("Hora: "+formatar(hh%12)+":"+formatar(mm)+":"+formatar(ss)); <<== Usar este modelo quando quizer horario (am - pm)
    }

    public String formatar(int num) {
        formato = new DecimalFormat("00");
        return formato.format(num);
    }

    private void funcionariosjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionariosjMenuItemActionPerformed
        // CHAMA O FORMULÁRIO CADASTRO DE FUNCIONÁRIOS

        JFFuncionarios oFormFunc = new JFFuncionarios();

        oFormFunc.setTitle("Cadastro funcionários");
        oFormFunc.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        oFormFunc.setLocationRelativeTo(null);
        oFormFunc.pack();
        oFormFunc.setVisible(true);
    }//GEN-LAST:event_funcionariosjMenuItemActionPerformed

    private void cadastroStatusjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroStatusjMenuItemActionPerformed
        // TODO add your handling code here:
        jFCadastroStatus oFormCadStatus = new jFCadastroStatus();

        oFormCadStatus.setTitle("Cadastro status");
        oFormCadStatus.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        oFormCadStatus.setLocationRelativeTo(null);
        oFormCadStatus.pack();
        oFormCadStatus.setVisible(true);
    }//GEN-LAST:event_cadastroStatusjMenuItemActionPerformed

    private void cadastroOperacoesjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroOperacoesjMenuItemActionPerformed
        // TODO add your handling code here:
        jFOperacao oFormOper = new jFOperacao();

        oFormOper.setTitle("Cadastro operações");
        oFormOper.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        oFormOper.setLocationRelativeTo(null);
        oFormOper.pack();
        oFormOper.setVisible(true);
    }//GEN-LAST:event_cadastroOperacoesjMenuItemActionPerformed

    private void cadastroCargosjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroCargosjMenuItemActionPerformed
        // TODO add your handling code here:

        jFCadastroCargos oCadCargo = new jFCadastroCargos();

        oCadCargo.setTitle("Cadastro de cargos");
        oCadCargo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        oCadCargo.setLocationRelativeTo(null);
        oCadCargo.pack();
        oCadCargo.setVisible(true);
    }//GEN-LAST:event_cadastroCargosjMenuItemActionPerformed

    private void cadastroCelulajMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroCelulajMenuItemActionPerformed
        // TODO add your handling code here:
        JFCadastroCelula oFormCadCel = new JFCadastroCelula();

        oFormCadCel.setTitle("Cadastro de células.");
        oFormCadCel.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        oFormCadCel.setLocationRelativeTo(null);
        oFormCadCel.pack();
        oFormCadCel.setVisible(true);
    }//GEN-LAST:event_cadastroCelulajMenuItemActionPerformed

    private void funcionariosjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionariosjButtonActionPerformed
        // TODO add your handling code here:
        funcionariosjMenuItemActionPerformed(evt);
    }//GEN-LAST:event_funcionariosjButtonActionPerformed

    private void cadastroStatusjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroStatusjButtonActionPerformed
        // TODO add your handling code here:
        cadastroStatusjMenuItemActionPerformed(evt);
    }//GEN-LAST:event_cadastroStatusjButtonActionPerformed

    private void cadastroCargosjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroCargosjButtonActionPerformed
        // TODO add your handling code here:
        cadastroCargosjMenuItemActionPerformed(evt);
    }//GEN-LAST:event_cadastroCargosjButtonActionPerformed

    private void jButtoncadastroCelulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncadastroCelulasActionPerformed
        // TODO add your handling code here:
        cadastroCelulajMenuItemActionPerformed(evt);
    }//GEN-LAST:event_jButtoncadastroCelulasActionPerformed

    private void cadastroOperacoesjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroOperacoesjButtonActionPerformed
        // TODO add your handling code here:
        cadastroOperacoesjMenuItemActionPerformed(evt);
    }//GEN-LAST:event_cadastroOperacoesjButtonActionPerformed

    private void sairDoSistemajMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairDoSistemajMenuItemActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_sairDoSistemajMenuItemActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        menuArquivojMenu.grabFocus();
        usuarioLogadojLabel.setText(" Usuário logado: " + System.getProperty("user.name"));
    }//GEN-LAST:event_formWindowOpened

    private void fmajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fmajButtonActionPerformed
        // TODO add your handling code here:
        
//        JOptionPane.showMessageDialog(null, "Essa parte ainda está em desenvolvimento.", "Mensagem dos sistema", JOptionPane.INFORMATION_MESSAGE);
        
        ModeloExcel modeloE = new ModeloExcel();
        VistaExcel vistaE = new VistaExcel();
        
        ControladorExcel oContraExcel = new ControladorExcel(vistaE, modeloE);
        
        vistaE.setVisible(true);
        vistaE.setLocationRelativeTo(null);
        vistaE.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_fmajButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        jFMop oFormMop = new jFMop();
        
        oFormMop.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        oFormMop.setLocationRelativeTo(null);
        oFormMop.pack();
        oFormMop.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new JFHome().setVisible(true);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastroCargosjButton;
    private javax.swing.JMenuItem cadastroCargosjMenuItem;
    private javax.swing.JMenuItem cadastroCelulajMenuItem;
    private javax.swing.JButton cadastroOperacoesjButton;
    private javax.swing.JMenuItem cadastroOperacoesjMenuItem;
    private javax.swing.JButton cadastroStatusjButton;
    private javax.swing.JMenuItem cadastroStatusjMenuItem;
    private javax.swing.JButton fmajButton;
    private javax.swing.JButton funcionariosjButton;
    private javax.swing.JMenuItem funcionariosjMenuItem;
    private javax.swing.JLabel horajLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtoncadastroCelulas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu menuArquivojMenu;
    private javax.swing.JMenuItem sairDoSistemajMenuItem;
    private javax.swing.JLabel usuarioLogadojLabel;
    // End of variables declaration//GEN-END:variables
}
