/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package concatwfm;

import Classes.CadastroStatus;
import Classes.ClassConecta;
import Classes.ComboItem;
import Classes.Funcionarios;
import Classes.MOP;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luciano.benfica
 */
public class jFMop extends javax.swing.JFrame {

    /**
     * Creates new form jFMop
     */
    public jFMop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        matriculajTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nomejTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        gmidjTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        niceIDjTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        loginAvayajTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ccmsjTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        consultarjButton = new javax.swing.JButton();
        statusjComboBox = new javax.swing.JComboBox();
        supervisorjComboBox = new javax.swing.JComboBox();
        coordenadorjComboBox = new javax.swing.JComboBox();
        tierjComboBox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        gradeMopjTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jSplitPane1.setDividerLocation(140);
        jSplitPane1.setDividerSize(8);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setOneTouchExpandable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FILTROS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jLabel2.setText("Matrícula");

        nomejTextField.setBackground(new java.awt.Color(255, 255, 204));
        nomejTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomejTextFieldKeyReleased(evt);
            }
        });

        jLabel3.setText("Nome do agente");

        jLabel4.setText("GMID");

        jLabel5.setText("Id nice");

        jLabel6.setText("Login Avaya");

        jLabel7.setText("CCMS");

        jLabel8.setText("Status");

        jLabel9.setText("Supervisor");

        jLabel10.setText("Coordenador");

        jLabel11.setText("TIER");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel12.setText("Célula");

        consultarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/buscar.png"))); // NOI18N
        consultarjButton.setText("Consultar");
        consultarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarjButtonActionPerformed(evt);
            }
        });

        statusjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusjComboBoxActionPerformed(evt);
            }
        });

        supervisorjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supervisorjComboBoxActionPerformed(evt);
            }
        });

        coordenadorjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coordenadorjComboBoxActionPerformed(evt);
            }
        });

        tierjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tierjComboBoxActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(matriculajTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel11)
                    .addComponent(tierjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gmidjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(niceIDjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(loginAvayajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ccmsjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7))))
                            .addComponent(consultarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(statusjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(supervisorjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(coordenadorjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton1)))
                    .addComponent(jLabel12))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matriculajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gmidjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(niceIDjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginAvayajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ccmsjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supervisorjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coordenadorjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(consultarjButton)
                        .addComponent(jButton1))
                    .addComponent(tierjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(jPanel1);

        gradeMopjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(gradeMopjTable);

        jSplitPane1.setRightComponent(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ClassConecta conecta = new ClassConecta();
    private ComboItem combo_status = null;
    private ComboItem combo_supervisor = null;
    private ComboItem combo_coordenador = null;

    public void getGrandeMOP() throws ParseException, SQLException {
        //Consultar pedidos
        MOP oMop = new MOP();

        /**
         * recebe os dados dos campos para realizar os filtros*
         */
        try {
            if (nomejTextField.getText().length() > 0) {
                oMop.setNome(nomejTextField.getText().trim() + "%");
            }
            if (gmidjTextField.getText().length() > 0) {
                oMop.setGmid(gmidjTextField.getText().trim() + "%");
            }
            if (matriculajTextField.getText().length() != 0) {

                oMop.setMatricula(Integer.valueOf(matriculajTextField.getText().trim()));
            }
            if (niceIDjTextField.getText().length() > 0) {
                oMop.setNiceid(Integer.valueOf(niceIDjTextField.getText().trim()));
            }
            if (loginAvayajTextField.getText().length() > 0) {
                oMop.setLogin_avaya(Integer.valueOf(loginAvayajTextField.getText().trim()));
            }
            if (ccmsjTextField.getText().length() > 0) {
                oMop.setIdccms(Integer.valueOf(ccmsjTextField.getText().trim()));
            }

            if (statusjComboBox.getItemCount() != 0 && !statusjComboBox.getSelectedItem().equals("TODOS")) {
                combo_status = null;
                combo_status = (ComboItem) statusjComboBox.getSelectedItem();
                
                oMop.setStatus_id(combo_status.getId());
            }
            
            if (supervisorjComboBox.getItemCount() != 0 && !supervisorjComboBox.getSelectedItem().equals("TODOS")) {
                combo_supervisor = null;
                combo_supervisor = (ComboItem) supervisorjComboBox.getSelectedItem();
                
                oMop.setSupervisor(combo_supervisor.toString());
            }
            if (coordenadorjComboBox.getItemCount() != 0 && !coordenadorjComboBox.getSelectedItem().equals("TODOS")) {
                combo_coordenador = null;
                combo_coordenador = (ComboItem) coordenadorjComboBox.getSelectedItem();
                
                oMop.setCoordenador(combo_coordenador.toString());
            }
            
            if(tierjComboBox.getItemCount() != 0 && !tierjComboBox.getSelectedItem().equals("TODOS")){
                
                oMop.setGrupo(tierjComboBox.getSelectedItem().toString());
            }

        } catch (NumberFormatException e) {
            System.err.println(e);
            JOptionPane.showMessageDialog(null, "Erro ao realizar consulta.\n" + e,
                    "Mensagem do sistema", JOptionPane.ERROR_MESSAGE);
        }

        ResultSet resultSet = null;

        String[] colunasTabela = new String[]{"Matrícula", "GMID", "Nice", "Login avaya", "Nome", "Data admissão", "CCMS", "Status",
            "Supervisor", "Coordenador", "Célula", "TIER"};
        DefaultTableModel modeloTabela = new DefaultTableModel(null, colunasTabela) {

            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        gradeMopjTable.setModel(modeloTabela);
        gradeMopjTable.getColumnModel().getColumn(0).setPreferredWidth(60);
        gradeMopjTable.getColumnModel().getColumn(1).setPreferredWidth(60);
        gradeMopjTable.getColumnModel().getColumn(2).setPreferredWidth(60);
        gradeMopjTable.getColumnModel().getColumn(3).setPreferredWidth(80);
        gradeMopjTable.getColumnModel().getColumn(4).setPreferredWidth(350);
        gradeMopjTable.getColumnModel().getColumn(5).setPreferredWidth(80);
        gradeMopjTable.getColumnModel().getColumn(6).setPreferredWidth(70);
        gradeMopjTable.getColumnModel().getColumn(7).setPreferredWidth(80);
        gradeMopjTable.getColumnModel().getColumn(8).setPreferredWidth(300);
        gradeMopjTable.getColumnModel().getColumn(9).setPreferredWidth(250);
        gradeMopjTable.getColumnModel().getColumn(10).setPreferredWidth(250);
        gradeMopjTable.getColumnModel().getColumn(11).setPreferredWidth(80);

        gradeMopjTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        try {

            resultSet = oMop.getConsultar();

            if (resultSet.getRow() == 1) {
                resultSet.first();
            }

        } catch (SQLException ex) {
            Logger.getLogger(Funcionarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {

            while (resultSet.next()) {

                Date hiredat = resultSet.getDate("HIREDATE");

                String hiredate;

                SimpleDateFormat formatoDataLanc = new SimpleDateFormat("dd/MM/yyyy");
                hiredate = formatoDataLanc.format(hiredat);

                modeloTabela.addRow(new String[]{
                    resultSet.getString("MATRICULA"),
                    resultSet.getString("GMID"),
                    resultSet.getString("NICEID"),
                    resultSet.getString("LOGIN_AVAYA"),
                    resultSet.getString("NOME"),
                    hiredate,
                    resultSet.getString("IDCCMS"),
                    resultSet.getString("STATUS_NAME"),
                    resultSet.getString("SUPERVISOR"),
                    resultSet.getString("COORDENADOR"),
                    resultSet.getString("CELULA"),
                    resultSet.getString("GRUPO"),});

            }

        } catch (SQLException ex) {
            Logger.getLogger(MOP.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void getConsultarGrade() throws SQLException {
        try {
            getGrandeMOP();
        } catch (ParseException e) {
            System.err.println(e);
            JOptionPane.showMessageDialog(null, "Erro ao carregar a grade.\n" + e,
                    "Mensagem do sistema", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void atualizaComboStatus() {
        try {
            CadastroStatus oCadStatus = new CadastroStatus();
            ResultSet rs;
            rs = oCadStatus.getConsultar();
            statusjComboBox.removeAllItems();
            statusjComboBox.addItem("TODOS");
            while (rs.next()) {
                statusjComboBox.addItem(new ComboItem(rs.getInt(1), rs.getString(2)));
            }
            statusjComboBox.updateUI();
        } catch (SQLException ex) {
            Logger.getLogger(jFMop.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void atualizaComboSupervisor() {
        try {
            MOP oMop = new MOP();
            ResultSet rs;
            rs = oMop.getConsultarSupervisor();
            supervisorjComboBox.removeAllItems();
            supervisorjComboBox.addItem("TODOS");
            while (rs.next()) {
                supervisorjComboBox.addItem(new ComboItem(rs.getInt("MATRICULA"), rs.getString("NOME")));
            }
            supervisorjComboBox.updateUI();
        } catch (SQLException ex) {
            Logger.getLogger(jFMop.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void atualizaComboCoordenador() {
        try {
            MOP oMop = new MOP();
            ResultSet rs;
            rs = oMop.getConsultarCoordenador();
            coordenadorjComboBox.removeAllItems();
            coordenadorjComboBox.addItem("TODOS");
            while (rs.next()) {
                coordenadorjComboBox.addItem(new ComboItem(rs.getInt("MATRICULA"), rs.getString("NOME")));
            }
            coordenadorjComboBox.updateUI();
        } catch (SQLException ex) {
            Logger.getLogger(jFMop.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void atualizaComboTIER() {
        try {
            MOP oMop = new MOP();
            ResultSet rs;
            rs = oMop.getConsultarTIER();
            tierjComboBox.removeAllItems();
            tierjComboBox.addItem("TODOS");
            while (rs.next()) {
                tierjComboBox.addItem(rs.getString("GRUPO"));
            }
            tierjComboBox.updateUI();
        } catch (SQLException ex) {
            Logger.getLogger(jFMop.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {
            ClassConecta.conecta();
        } catch (Exception e) {
            System.err.println(e);
            JOptionPane.showMessageDialog(null, "Erro ao abrir conexão com o banco de dados.\n" + e,
                    "Mensagem do sistema", JOptionPane.ERROR_MESSAGE);
        }
        try {
            getConsultarGrade();
        } catch (SQLException ex) {
            Logger.getLogger(jFMop.class.getName()).log(Level.SEVERE, null, ex);
        }
        atualizaComboStatus();
        atualizaComboSupervisor();
        atualizaComboCoordenador();
        atualizaComboTIER();
    }//GEN-LAST:event_formWindowOpened

    private void consultarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarjButtonActionPerformed
        // TODO add your handling code here:
        try {
            getGrandeMOP();
        } catch (SQLException | ParseException e) {
            JOptionPane.showMessageDialog(null, "Erro ao realizar a consulta.\n" + e,
                    "Mensagem do sistema", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_consultarjButtonActionPerformed

    private void nomejTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomejTextFieldKeyReleased
        // TODO add your handling code here:
        try {
            MOP oMop = new MOP();
            oMop.setNome(nomejTextField.getText());
            ResultSet rs = null;
            rs = oMop.getConsultar();
            getGrandeMOP();
        } catch (ParseException | SQLException ex) {
            Logger.getLogger(jFMop.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_nomejTextFieldKeyReleased

    private void statusjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusjComboBoxActionPerformed
        // TODO add your handling code here:
        consultarjButtonActionPerformed(evt);
    }//GEN-LAST:event_statusjComboBoxActionPerformed

    private void supervisorjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supervisorjComboBoxActionPerformed
        // TODO add your handling code here:
        consultarjButtonActionPerformed(evt);
    }//GEN-LAST:event_supervisorjComboBoxActionPerformed

    private void coordenadorjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coordenadorjComboBoxActionPerformed
        // TODO add your handling code here:
        consultarjButtonActionPerformed(evt);
    }//GEN-LAST:event_coordenadorjComboBoxActionPerformed

    private void tierjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tierjComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tierjComboBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, tierjComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFMop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFMop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFMop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFMop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new jFMop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ccmsjTextField;
    private javax.swing.JButton consultarjButton;
    private javax.swing.JComboBox coordenadorjComboBox;
    private javax.swing.JTextField gmidjTextField;
    private javax.swing.JTable gradeMopjTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField loginAvayajTextField;
    private javax.swing.JTextField matriculajTextField;
    private javax.swing.JTextField niceIDjTextField;
    private javax.swing.JTextField nomejTextField;
    private javax.swing.JComboBox statusjComboBox;
    private javax.swing.JComboBox supervisorjComboBox;
    private javax.swing.JComboBox tierjComboBox;
    // End of variables declaration//GEN-END:variables
}
